[package]
name = "wasi-io-test"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen-rt = { version = "0.43.0", features = ["bitflags"] }

[package.metadata.component]
package = "test:wasi-io"

[package.metadata.component.target.dependencies]
"wasi:io" = { path = "./wit/deps/wasi-io" }
"theater:simple" = { path = "./wit/deps/theater-simple" }
