name = "simple-timing-test"
version = "0.1.0"
component = "/Users/colinrozzi/work/theater/crates/theater-handler-timing/test-actors/simple-timing-test/target/wasm32-wasip1/release/simple_timing_test.wasm"
description = "Simple test actor for theater:simple/timing interface"
save_chain = true

[[handler]]
type = "runtime"

[[handler]]
type = "timing"
