name = "environment-test-replay"
version = "0.1.0"
component = "/Users/colinrozzi/work/theater/crates/theater-handler-environment/test-actors/environment-test/./target/wasm32-unknown-unknown/release/environment_test.wasm"
description = "Environment handler replay test"
save_chain = true

[[handler]]
type = "runtime"

[[handler]]
type = "replay"
chain = "/Users/colinrozzi/work/theater/environment-test-chain.json"
