name = "wasi-clocks-test"
version = "0.1.0"
package = "/Users/colinrozzi/work/theater/crates/theater-handler-timing/test-actors/wasi-clocks-test/target/wasm32-unknown-unknown/release/wasi_clocks_test.wasm"
description = "WASI clocks and poll interface test actor - REPLAY"
save_chain = true

[[handler]]
type = "replay"
chain = "/Users/colinrozzi/work/theater/crates/theater-handler-timing/test-actors/wasi-clocks-test/chain.json"
