name = "runtime-test-replay"
version = "0.1.0"
component = "/Users/colinrozzi/work/theater/crates/theater-handler-runtime/test-actors/runtime-test/target/wasm32-unknown-unknown/release/runtime_test.wasm"
description = "Runtime handler replay test"
save_chain = true

[[handler]]
type = "runtime"

[[handler]]
type = "replay"
chain = "/Users/colinrozzi/work/theater/crates/theater-handler-runtime/test-actors/runtime-test/chain.json"
