name = "{{project_name}}"
version = "0.1.0"
package = "./target/wasm32-unknown-unknown/release/{{project_name_snake}}.wasm"
description = "A basic HTTP server built with Theater WebAssembly actors"

[[handler]]
type = "runtime"

[[handler]]
type = "http-framework"
