name = "wasi-http-test"
version = "0.1.0"
component = "./target/wasm32-unknown-unknown/release/wasi_http_test.wasm"
save_chain = true

[[handler]]
type = "runtime"

[[handler]]
type = "wasi-http"
port = 8080
host = "127.0.0.1"
