name = "composite-test"
version = "0.1.0"
package = "/Users/colinrozzi/work/theater/test-actors/composite-test/target/wasm32-unknown-unknown/release/composite_test_actor.wasm"
description = "Test actor for Composite runtime"

[[handler]]
type = "runtime"
