name = "wasi-http-test"
version = "0.1.0"
package = "/Users/colinrozzi/work/theater/crates/theater-handler-http/test-actors/wasi-http-test/./target/wasm32-unknown-unknown/release/wasi_http_test.wasm"
save_chain = true

[[handler]]
type = "replay"
chain = "/Users/colinrozzi/work/theater/crates/theater-handler-http/test-actors/wasi-http-test/chains/two.json"
